ch_cookie_consent:
    theme: 'light' # light, dark
    categories: # Below are the default supported categories
        - 'analytics'
        - 'social_media'
    use_logger: true # Logs user actions to database
    position: 'bottom' # top, bottom