ckfinder:
  connector:
    licenseName: '%env(LISCENCE_NAME))%'
    licenseKey: '%env(LISCENCE_KEY)%'
    authenticationClass: App\CustomCKFinderAuth\CustomCKFinderAuth
    resourceTypes:
      Images:
        name: contrib
        backend: default
        directory: contrib