easy_admin:
    site_name: '<img style="max-width:15%;" src="/vegefoods/vegefoods/images/logo-Atelier_am.PNG"/><span style="margin-left: 15px;">Administration du site</span>'

    user:
        name_property_path: 'email'
        display_avatar: false

    design:
        menu:
            - { label: "Page d'accueil"}
            - { entity: "SlideContrib", label: 'Les slides', icon: 'picture-o'}
            - { entity: "Testimony", label: 'Les irréductibles', icon: 'users'}
            - { entity: "Partner", label: 'Les partenaires', icon: 'weixin'}
            - { label: 'Pages Activités'}
            - { entity: 'CoworkingContrib', params: { action: 'edit', id: 2 },  label: 'Page Coworking', icon: 'coffee'}
            - { entity: 'FablabContrib', params: { action: 'edit', id: 2 }, label: 'Page FabLab', icon: 'wrench'}
            - { entity: 'FormationContrib', params: { action: 'edit', id: 2 }, label: 'Page Formation', icon: 'certificate'}
            - { label: 'Le Blog'}
            - { entity: 'BlogArticle', params: { action: 'new' }, label: 'Ajouter un article', icon: 'plus'}
            - { entity: 'BlogArticle', label: 'Nos articles', icon: 'book'}
            - { entity: 'Tag', params: { action: 'new' }, label: 'Ajouter une catégorie', icon: 'tags'}
            - { entity: 'BlogContrib', params: { action: 'edit', id: 1 }, label: "Modifier l'entête", icon: 'picture-o'}
            - { label: 'Gestion utilisateur'}
            - { entity: 'User', label: 'Utilisateurs', icon: 'user'}
            - { entity: 'NewsLetter', params: { action: 'list'}, label: 'Les abonnées', icon: 'users'}
            - { entity: 'Contact', params: { action: 'list'}, label: 'Prise de contact', icon: 'users'}
            - { label: 'Raccourci'}
            - { label: 'Accéder au Site', route: 'app_home', icon: 'external-link-square', target: '_blank'}
            #- { label: 'Mettre le site en maintenance', route: 'app_busy', icon: 'external-link-square', target: '_blank'}

        brand_color: '#aa3e98'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'

    entities:
        SlideContrib:
            class: App\Entity\SlideContrib
            label: "Slide"
            form:
                title: "Ajouter une slide"
                fields:
                    - { property: 'title', type: 'text', label: 'Titre de la slide' }
                    - { property: 'legend', type: 'text', label: 'Légende' }
                    - { property: 'imgFile', type: 'vich_image', base_path: '/images/home/carousel' }
                    - { property: 'priority', type: 'integer', label: 'Priorité'}
                    - { property: 'published', label: 'Publier'}
            list:
                title: "Les Slides"
                fields: ['id', 'title', 'priority', { property: 'image', type: 'image', height: 'lg', base_path: '/images/home/carousel' }, 'published']

        Testimony:
            class: App\Entity\Testimony
            label: "Les Membres"
            form:
                title: "Ajouter un Membres"
                fields:
                    - { property: 'fullname', type: 'text', label: 'Nom et prénom' }
                    - { property: 'position', type: 'text', label: 'Métier / Position' }
                    - { property: 'text', type: 'text', label: 'citation' }
                    - { property: 'imgFile', type: 'vich_image', base_path: '/images/home/testimony'}
                    - { property: 'testimonyType', type: 'choice', type_options: { mapped: true, expanded: true, multiple: false, choices: { 'Maker': 0, 'Coworker': 1, 'Formateur': 2, 'Irreductible': 3 }}}
            list:
                title: "Les Irreductibles"
                fields: ['id', 'fullname', 'position', 'TestimonyLabel', 'text', { property: 'image', type: 'image', height: 'lg', base_path: '/images/home/testimony' }]
            edit:
                title: "Modifier un Irréductible"

        Partner:
            class: App\Entity\Partner
            label: "Les Partenaires"
            form:
                title: "Ajouter un partenaire"
                fields:
                    - { property: 'link', type: 'text', label: 'Lien de redirection' }
                    - { property: 'imgFile', type: 'vich_image', base_path: '/images/home/partner'}
            list:
                title: "Les Partenaires"
                fields: ['id', 'link', { property: 'image', type: 'image', height: 'lg', base_path: '/images/home/partner' }]

        CoworkingContrib:
            class: App\Entity\CoworkingContrib
            label: "Page coworking"
            disabled_actions: ['search', 'delete', 'new', 'list']
            form:
                title: "Mettre à jour la page coworking"
                fields:
                    - { type: 'group', columns: 6, label: "Entête" }
                    - { property: 'imgHeaderFile', type: 'vich_image', base_path: '/images/coworking', label: "Image d'entête"}
                    - { property: 'titleHeader', type: 'text', label: 'Titre entête' }
                    - { type: 'section', label: "Image de présentation et Vidéo" }
                    - { property: 'imgVideoFile', type: 'vich_image', base_path: '/images/coworking', label: "Image vidéo"}
                    - { property: 'videoLink', type: 'text', label: 'Lien de la vidéo' }
                    - { type: 'group', columns: 6, label: "Contenu" }
                    - { property: 'titlePres', type: 'text', label: 'Titre de présentation' }
                    - { property: 'textPres', type: 'text_editor', label: 'Texte de présentation' }
                    - { type: 'group', columns: 6, label: "Chiffre clé" }
                    - { property: 'imageKeynumberFile', type: 'vich_image', base_path: '/images/coworking', label: "Image banierre des chiffres clé"}
                    - { property: 'keynumber1', type: 'integer', label: 'Chiffre clé n°1' }
                    - { property: 'labelKeynumber1', type: 'text', label: 'Label du chiffre clé n°1' }
                    - { property: 'keynumber2', type: 'integer', label: 'Chiffre clé n°2' }
                    - { property: 'labelKeynumber2', type: 'text', label: 'Label du chiffre clé n°2' }
                    - { property: 'keynumber3', type: 'integer', label: 'Chiffre clé n°3' }
                    - { property: 'labelKeynumber3', type: 'text', label: 'Label du chiffre clé n°3' }
                    - { property: 'keynumber4', type: 'integer', label: 'Chiffre clé n°4' }
                    - { property: 'labelKeynumber4', type: 'text', label: 'Label du chiffre clé n°4' }
                    - { type: 'group', columns: 6, label: "Section Tarifs" }
                    - { property: 'titleTarif', type: 'text', label: 'Titre de la section Tarif' }
                    - { property: 'tarifs', type: 'text_editor', label: 'Contenu de la section Tarif' }


        FablabContrib:
            class: App\Entity\FablabContrib
            label: "Page FabLab"
            disabled_actions: ['search', 'delete', 'list', 'new']
            form:
                title: "Mettre à jour la page FabLab"
                fields:
                    - { type: 'group', columns: 6, label: "Entête" }
                    - { property: 'imgHeaderFile', type: 'vich_image', base_path: '/images/fablab', label: "Image d'entête"}
                    - { property: 'titleHeader', type: 'text', label: 'Titre entête' }
                    - { property: 'imgVideoFile', type: 'vich_image', base_path: '/images/fablab', label: "Image vidéo"}
                    - { property: 'videoLink', type: 'text', label: 'Lien de la vidéo' }
                    - { type: 'group', columns: 6, label: "Contenu" }
                    - { property: 'titlePres', type: 'text', label: 'Titre de présentation' }
                    - { property: 'textPres', type: 'text_editor', label: 'Texte de présentation' }
                    - { type: 'group', columns: 6, label: "Chiffre clé" }
                    - { property: 'imageKeynumberFile', type: 'vich_image', base_path: '/images/fablab', label: "Image banierre des chiffres clé"}
                    - { property: 'keynumber1', type: 'integer', label: 'Chiffre clé n°1' }
                    - { property: 'labelKeynumber1', type: 'text', label: 'Label du chiffre clé n°1' }
                    - { property: 'keynumber2', type: 'integer', label: 'Chiffre clé n°2' }
                    - { property: 'labelKeynumber2', type: 'text', label: 'Label du chiffre clé n°2' }
                    - { property: 'keynumber3', type: 'integer', label: 'Chiffre clé n°3' }
                    - { property: 'labelKeynumber3', type: 'text', label: 'Label du chiffre clé n°3' }
                    - { property: 'keynumber4', type: 'integer', label: 'Chiffre clé n°4' }
                    - { property: 'labelKeynumber4', type: 'text', label: 'Label du chiffre clé n°4' }
                    - { type: 'group', columns: 6, label: "Section Tarifs" }
                    - { property: 'titleTarif', type: 'text', label: 'Titre de la section Tarif' }
                    - { property: 'tarifs', type: 'text_editor', label: 'Contenu de la section Tarif' }

        FormationContrib:
            class: App\Entity\FormationContrib
            label: "Page Formation"
            disabled_actions: ['search', 'delete', 'list', 'new']
            form:
                title: "Mettre à jour la page Formation"
                fields:
                    - { type: 'group', columns: 6, label: "Entête" }
                    - { property: 'imgHeaderFile', type: 'vich_image', base_path: '/images/formation', label: "Image d'entête"}
                    - { property: 'titleHeader', type: 'text', label: 'Titre entête' }
                    - { property: 'imgVideoFile', type: 'vich_image', base_path: '/images/formation', label: "Image vidéo"}
                    - { property: 'videoLink', type: 'text', label: 'Lien de la vidéo' }
                    - { type: 'group', columns: 6, label: "Contenu" }
                    - { property: 'titlePres', type: 'text', label: 'Titre de présentation' }
                    - { property: 'textPres', type: 'text_editor', label: 'Texte de présentation' }
                    - { type: 'group', columns: 6, label: "Chiffre clé" }
                    - { property: 'imageKeynumberFile', type: 'vich_image', base_path: '/images/formation', label: "Image banierre des chiffres clé"}
                    - { property: 'keynumber1', type: 'integer', label: 'Chiffre clé n°1' }
                    - { property: 'labelKeynumber1', type: 'text', label: 'Label du chiffre clé n°1' }
                    - { property: 'keynumber2', type: 'integer', label: 'Chiffre clé n°2' }
                    - { property: 'labelKeynumber2', type: 'text', label: 'Label du chiffre clé n°2' }
                    - { property: 'keynumber3', type: 'integer', label: 'Chiffre clé n°3' }
                    - { property: 'labelKeynumber3', type: 'text', label: 'Label du chiffre clé n°3' }
                    - { property: 'keynumber4', type: 'integer', label: 'Chiffre clé n°4' }
                    - { property: 'labelKeynumber4', type: 'text', label: 'Label du chiffre clé n°4' }

        BlogContrib:
            class: App\Entity\BlogContrib
            label: "Page Blog"
            disabled_actions: ['search', 'delete', 'list', 'new']
            form:
                title: "Mettre à jour la page Blog"
                fields:
                    - { property: 'imageBannerFile', type: 'vich_image', base_path: '/images/blog', label: "Image d'entête (banniere)"}
                    - { property: 'titleBanner', type: 'text', label: 'Titre entête' }

        BlogArticle:
            class: App\Entity\BlogArticle
            label: "Article"
            form:
                title: "Ajouter un article"
                fields:
                    - { property: 'title', type: 'text'}
                    - { property: 'text', type: 'text_editor'}
                    - { property: 'tags', type: 'easyadmin_autocomplete'}
                    - { property: 'imgFile', type: 'vich_image', base_path: '/images/blog'}
                    - { property: 'publicationDate', type: 'date'}

            list:
                title: "Article les plus récent"
                fields: ['id', 'title', 'publicationDate', { property: 'filename', type: 'image', height: 'lg', base_path: '/images/blog' }]

            edit:
                title: "Modifier l'article"

        Tag:
            label: "Catégorie"
            class: App\Entity\Tag
            form:
              fields:
                - { property: 'name', type: 'text' }

        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            label: 'Utilisateur'
            list:
                title: "Utilisateurs les plus récent"
            form:
                title: "Ajouter un utilisateur"
                fields:
                    - { property: 'email' }
                    - property: 'password'
                      type: 'repeated'
                      type_options:
                          type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                          required: false
                          first_options: { label: 'Mot de passe' }
                          second_options: { label: 'Confirmer le mot de passe' }
                          invalid_message: fos_user.password.mismatch
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices: { 'Administrateur': 'ROLE_ADMIN' }
                edit: "Editer un utilisateur"
        NewsLetter:
                    class: App\Entity\NewsLetter
                    label: 'Les abonnés à la NewsLetter'
                    disabled_actions: ['search', 'delete', 'edit', 'new']
                    list:
                        title: "Les abonnés à la NewsLetter"

        Contact:
                    class: App\Entity\Contact
                    label: 'Contact via le site'
                    disabled_actions: ['search', 'delete', 'edit', 'new']
                    list:
                        title: "Prise de contact via le site vitrine"
                        fields: ['id', 'username', 'email', 'subject', 'message']
