vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
