vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
        home_carousel_image:
            uri_prefix: /images/home/carousel
            upload_destination: '%kernel.project_dir%/public/images/home/carousel'
        home_testimony_image:
            uri_prefix: /images/home/testimony
            upload_destination: '%kernel.project_dir%/public/images/home/testimony'
        home_partner_image:
            uri_prefix: /images/home/partner
            upload_destination: '%kernel.project_dir%/public/images/home/partner'